import { describe, expect, it } from 'vitest'
import {
  DEFAULT_SCRIPT_API_PORT,
  SCRIPT_API_LISTEN_ADDRESS,
  SCRIPT_OUTLET_GROUP_PREFIX
} from '../../shared/appConfig'
import {
  canStartScriptApi,
  extractBearerToken,
  generateScriptApiToken,
  getScriptApiBaseUrl,
  isAuthorized,
  isGeneratedOutletGroup,
  isLoopbackAddress,
  normalizeScriptApiConfig,
  safeCompare
} from './scriptApi'

describe('normalizeScriptApiConfig', () => {
  it('falls back to the default port when the port is invalid', () => {
    expect(normalizeScriptApiConfig(undefined).port).toBe(DEFAULT_SCRIPT_API_PORT)
    expect(normalizeScriptApiConfig({ port: 0 }).port).toBe(DEFAULT_SCRIPT_API_PORT)
    expect(normalizeScriptApiConfig({ port: 70000 }).port).toBe(DEFAULT_SCRIPT_API_PORT)
    expect(normalizeScriptApiConfig({ port: 1.5 }).port).toBe(DEFAULT_SCRIPT_API_PORT)
    expect(normalizeScriptApiConfig({ port: 17891 }).port).toBe(17891)
  })

  it('treats enable as opt-in and autoCloseConnection as opt-out', () => {
    expect(normalizeScriptApiConfig(undefined).enable).toBe(false)
    expect(normalizeScriptApiConfig({ enable: true }).enable).toBe(true)
    expect(normalizeScriptApiConfig(undefined).autoCloseConnection).toBe(true)
    expect(normalizeScriptApiConfig({ autoCloseConnection: false }).autoCloseConnection).toBe(false)
  })

  it('trims the token so whitespace-only input is treated as empty', () => {
    expect(normalizeScriptApiConfig({ token: '  abc  ' }).token).toBe('abc')
    expect(normalizeScriptApiConfig({ token: '   ' }).token).toBe('')
  })
})

describe('canStartScriptApi', () => {
  it('refuses to start without a token', () => {
    expect(canStartScriptApi(normalizeScriptApiConfig({ enable: true, token: '' }))).toBe(false)
    expect(canStartScriptApi(normalizeScriptApiConfig({ enable: true, token: '  ' }))).toBe(false)
  })

  it('requires both enable and a token', () => {
    expect(canStartScriptApi(normalizeScriptApiConfig({ enable: false, token: 'abc' }))).toBe(false)
    expect(canStartScriptApi(normalizeScriptApiConfig({ enable: true, token: 'abc' }))).toBe(true)
  })
})

describe('safeCompare', () => {
  it('returns false for different lengths without throwing', () => {
    expect(safeCompare('abc', 'abcd')).toBe(false)
    expect(safeCompare('', 'a')).toBe(false)
  })

  it('compares content exactly', () => {
    expect(safeCompare('abc', 'abc')).toBe(true)
    expect(safeCompare('abc', 'abd')).toBe(false)
    expect(safeCompare('', '')).toBe(true)
  })
})

describe('extractBearerToken', () => {
  it('accepts both the Bearer prefix and a bare token', () => {
    expect(extractBearerToken('Bearer abc')).toBe('abc')
    expect(extractBearerToken('bearer   abc  ')).toBe('abc')
    expect(extractBearerToken('abc')).toBe('abc')
    expect(extractBearerToken(undefined)).toBe('')
  })
})

describe('isAuthorized', () => {
  it('rejects everything when the expected token is empty', () => {
    expect(isAuthorized('Bearer abc', '')).toBe(false)
    expect(isAuthorized(undefined, '')).toBe(false)
  })

  it('accepts only the exact token', () => {
    expect(isAuthorized('Bearer abc', 'abc')).toBe(true)
    expect(isAuthorized('abc', 'abc')).toBe(true)
    expect(isAuthorized('Bearer abcd', 'abc')).toBe(false)
    expect(isAuthorized(undefined, 'abc')).toBe(false)
  })
})

describe('isLoopbackAddress', () => {
  it('accepts IPv4, IPv6 and IPv4-mapped loopback addresses', () => {
    expect(isLoopbackAddress('127.0.0.1')).toBe(true)
    expect(isLoopbackAddress('127.0.0.2')).toBe(true)
    expect(isLoopbackAddress('::1')).toBe(true)
    expect(isLoopbackAddress('::ffff:127.0.0.1')).toBe(true)
  })

  it('rejects non-loopback and empty addresses', () => {
    expect(isLoopbackAddress('192.168.1.10')).toBe(false)
    expect(isLoopbackAddress('10.0.0.1')).toBe(false)
    expect(isLoopbackAddress(undefined)).toBe(false)
    expect(isLoopbackAddress('')).toBe(false)
  })
})

describe('generateScriptApiToken', () => {
  it('produces a 48-char lowercase hex string from 24 random bytes', () => {
    const token = generateScriptApiToken((size) => new Uint8Array(size).fill(0xab))
    expect(token).toHaveLength(48)
    expect(token).toMatch(/^[0-9a-f]{48}$/)
    expect(token).toBe('ab'.repeat(24))
  })

  it('zero-pads single-digit bytes', () => {
    const token = generateScriptApiToken((size) => new Uint8Array(size).fill(0x05))
    expect(token).toBe('05'.repeat(24))
  })
})

describe('isGeneratedOutletGroup', () => {
  it('only matches groups generated by script outlets', () => {
    expect(isGeneratedOutletGroup(`${SCRIPT_OUTLET_GROUP_PREFIX}7900`)).toBe(true)
    expect(isGeneratedOutletGroup('SCRIPT-POOL')).toBe(false)
    expect(isGeneratedOutletGroup('')).toBe(false)
  })
})

describe('getScriptApiBaseUrl', () => {
  it('always points at the loopback address', () => {
    expect(getScriptApiBaseUrl(17890)).toBe(`http://${SCRIPT_API_LISTEN_ADDRESS}:17890`)
  })
})
